### ISSUE TITLE
有点小吐槽

### ISSUE THREAD

**Issue by xctec** [dataease/installer#27]
听闻我朋友被这个项目坑了， 我来看看。 
fit2cloud 早期， 某种原因我就知道这个公司了，从当时的直觉来看，这应该是一个有心在做产品的公司。 
这个开源的产品， 本身应该是个不差的产品，但是，这个installer 里面的compose 写的实在太low了， 搞那么复杂， 挖那么深的坑。 

本身就只有几个服务， 重写个compose 也不是多麻烦。还是建议你们的负责人看到。 把原本的干掉， 重写个吧。 这个真的太。。。。。了。

**Comment by bestwxc** [comment]
研发不易， 不要被这种小细节败坏技术的名声。。。
