### ISSUE TITLE
判断剩余空间大小的写法存在问题

### ISSUE THREAD

**Issue by foolishflyfox** [dataease/installer#43]
https://github.com/dataease/installer/blob/b47090e18f4eaf48e11a799c6da61a1fde32d498/dataease/install.sh#L38

在 shell 编程时，对于浮点变量的比较，不能使用 `if [[ $v1 < $v2 ]]` 的方式，这种方式对变量进行字符比较，会造成 4.9 < 20.0 为 false 的错误结果。

建议将 `if [[ $available_disk < 20.0 ]];then` 修改为 `if (( $(echo "$available_disk < 20.0" | bc -l) ));then`。我在 ubuntu 20.04 下测试过，参考文档 [shell if 浮点数比较](https://www.cnblogs.com/shixun/p/6179642.html)

此if判断语句还有另一种写法: `if (( $(bc -l <<< "$available_disk < 20.0") ));then`

**Comment by fit2cloudrd** [comment]
感谢反馈，我们之前的判断是使用bc的，但由于用户反馈某些操作系统中不包含bc命令，所以后来我们调整了判断方式。目前已经修复了，请等待新版本发布。
